language: python
dist: xenial
python:
  - 3.6
  - 3.7
addons:
  chrome: stable
matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
install:
  - pip install tox-travis
  - npm install -g jsdoc
before_script:
  - sudo bash ./scripts/setup_chromedriver.sh
  - sudo bash ./scripts/setup_geckodriver.sh
script:
  - tox -- --driver Chrome
  - tox -- --driver Firefox
branches:
  only:
  - master
